## Shamelessly stolen from Alan Storm https://github.com/astorm/magento2-travis
env:
    #global environmental variables control magento instal parameters
    #see also hosts in addons.
    global:
    - PULSESTORM_MAGE2_FAKE_URL=http://magento-2-travis.dev
    - PULSESTORM_MAGE2_ADMIN_EMAIL=ross.mitchell@example.com
    - PULSESTORM_MAGE2_ADMIN_FIRST_NAME=Ross
    - PULSESTORM_MAGE2_ADMIN_LAST_NAME=Mitchell
    - PULSESTORM_MAGE2_ADMIN_USERNAME=admin
    - PULSESTORM_MAGE2_ADMIN_PASSWORD=ih3artmagento
    - PULSESTORM_MAGE2_ADMIN_DBNAME=magento_2_travis
    - PULSESTORM_PESTLE_URL=http://pestle.pulsestorm.net
    - PULSESTORM_COMPOSER_REPOSITORY_TO_TEST=https://github.com/rossmitchell/module-twofactor
    - PULSESTORM_COMPOSER_PACKAGE_TO_TEST=rossmitchell/module-twofactor
    - MAGENTO_VERSION=2.1.7
addons:
  hosts:
    # should match PULSESTORM_MAGE2_FAKE_URL above
    - magento-2-travis.dev
language: php
sudo: required
dist: trusty
matrix:
  include:
    - php: 5.6
      env: GENERATE_COVERAGE="0"
    - php: 7.0
      env: GENERATE_COVERAGE="1"

cache:
  directories:
    - $HOME/.composer/cache
before_script:
    # some useful debugging stuff for travis
    #- curl http://magento-2-travis.dev/index.php
    #- curl http://magento-2-travis.dev/
    #- sudo find /var/log/apache2 -exec cat '{}' \;
    #- sudo cat /etc/apache2/sites-available/000-default.conf
    #- sudo cat /etc/apache2/sites-enabled/000-default.conf
    #- sudo apachectl -V
    #- sudo apache2ctl -V
    #- ls -lh $TRAVIS_BUILD_DIR
    #- sudo ls /etc/apache2/sites-available
    #- sudo ls /etc/apache2/sites-enabled
    #- pwd
    #
    # get latest composer
    - composer selfupdate
    # Create the composer Auth File
    - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
    # add multiverse support to get MySQL 5.6 update apt
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse" && sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
    - sudo apt-get update -qq
    # add mysql 5.6
    - sudo apt-get remove -y -qq --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5
    - sudo apt-get -y -qq autoremove;
    - sudo apt-get -y -qq autoclean;
    - sudo apt-get install -y -qq mysql-server-5.6 mysql-client-5.6;
    - mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE magento_2_travis;';
    # add apache
    - sudo apt-get install -y -qq apache2 libapache2-mod-fastcgi
    #   enable php-fpm -- www.conf.default is PHP 7 only, so we dev/null any copy problems
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf 2>/dev/null || true
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    #   awful hack used during travis debugging that I swear I'm going to remove
    #   but then again you're reading this so I didn't remove it and **sigh**
    - sudo chmod 777 /home /home/travis /home/travis/build

    #   configure apache virtual hosts, assumes 000-default.conf is there
    - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    # restart apache
    - sudo service apache2 restart

    # clone main magento github repository
    - composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition:${MAGENTO_VERSION} magento2
    # install Magento
    - cd magento2
    # switch to specific branch in you like
    #- git checkout 2.0;git checkout tags/2.0.2
    # add composer package under test, composer require will trigger update/install
    - composer config repositories.travis_to_test git $PULSESTORM_COMPOSER_REPOSITORY_TO_TEST
    - composer require -n $PULSESTORM_COMPOSER_PACKAGE_TO_TEST dev-master
    # run installation command using evn variables set above
    - php bin/magento setup:install --admin-email "$PULSESTORM_MAGE2_ADMIN_EMAIL" --admin-firstname "$PULSESTORM_MAGE2_ADMIN_FIRST_NAME" --admin-lastname "$PULSESTORM_MAGE2_ADMIN_LAST_NAME" --admin-password "$PULSESTORM_MAGE2_ADMIN_PASSWORD" --admin-user "$PULSESTORM_MAGE2_ADMIN_USERNAME" --backend-frontname admin --base-url "$PULSESTORM_MAGE2_FAKE_URL" --db-host 127.0.0.1 --db-name magento_2_travis --db-user root --session-save files --use-rewrites 1 --use-secure 0 -vvv
    - cp vendor/$PULSESTORM_COMPOSER_PACKAGE_TO_TEST/Tests/Integration/phpunit.twofactor.xml dev/tests/integration/phpunit.xml
    - mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE magento_integration_tests;'
    - cp dev/tests/integration/etc/install-config-mysql.travis.php.dist dev/tests/integration/etc/install-config-mysql.php

script:
    - bash $TRAVIS_BUILD_DIR/.travis/run-scripts.bash

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ ${GENERATE_COVERAGE} == "1" ]]; then php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/coverage.clover; fi
